{{- include "archy.validateValues" . -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "archy.fullname" . }}
  labels:
    {{- include "archy.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: {{ include "archy.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    clientConfig:
      service:
        name: {{ include "archy.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      {{- if eq .Values.certificates.method "external" }}
      caBundle: {{ .Values.certificates.external.caBundle }}
      {{- else if eq .Values.certificates.method "helm" }}
      caBundle: {{ include "archy.caBundle" . }}
      {{- else }}
      caBundle: ""
      {{- end }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values: [{{ include "archy.name" . | quote }}]
      {{- with .Values.webhook.objectSelector.matchExpressions }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "kube-public"]
      {{- with .Values.webhook.namespaceSelector.matchExpressions }}
        {{- toYaml . | nindent 8 }}
      {{- end }}