apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: archy-webhook
webhooks:
  - name: archy.lsdopen.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        name: archy-webhook
        namespace: default
        path: "/mutate"
      caBundle: Cg== # Placeholder, will be patched by Tilt
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    objectSelector:
      matchExpressions:
        - key: app
          operator: NotIn
          values: ["archy-webhook"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "kube-public"] # Avoid breaking system pods
